### ISSUE TITLE
global変数について

### ISSUE THREAD

**Issue by Ryo-Miyakawa** [c0a21149fe/ProjExD#2]
https://github.com/c0a21149fe/ProjExD/blob/cbffb35497d1b5167a7a84d4f995a1cdc4c85461/ex01/alphabet.py#L9

global変数をstart関数内に入れた理由を教えてほしい

**Comment by c0a21149fe** [comment]
len_allとlen_lostは入れる必要がないが、要件にグローバル変数として設定しろとあったため、わかりやすくするために入れた。
triedに関しては、関数内で値の変更を行うため、入れる必要があるよ。
