### ISSUE TITLE
例外処理の表示

### ISSUE THREAD

**Issue by c0a2103365** [c0a21149fe/ProjExD#3]
https://github.com/c0a21149fe/ProjExD/blob/f5b715adcd60eb1bdb8215e39b83756a61c7b59a/ex01/alphabet.py#L27
例外発生時の具体的な内容を表示したほうが良いと思います。

**Comment by c0a21149fe** [comment]
具体的な内容を示すとエラーログのようになってしまい、プレイヤーが驚いてしまう可能性が高いため、修正しません。
