### ISSUE TITLE
適切な変数名に変更

### ISSUE THREAD

**Issue by c0a2103365** [c0a21149fe/ProjExD#8]
https://github.com/c0a21149fe/ProjExD/blob/e5a3433c0f8de22f7da180a2b864d787f5fea330/ex04/dodge_bomb.py#L56

変数名が日本語（ローマ字）になので、英語（英単語）に変更したほうが良いと思います。

**Comment by c0a21149fe** [comment]
jikanをtimeにしてしまうと、モジュールとの区別がつけづらくなるため、修正しません。
